//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2/20/2013 6:50:43 PM
namespace ApressDemo.ApressODataService
{
    
    /// <summary>
    /// There are no comments for ApressBookDBEntities in the schema.
    /// </summary>
    public partial class ApressBookDBEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApressBookDBEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApressBookDBEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("ApressBookDBModel", global::System.StringComparison.Ordinal))
            {
                return global::System.Reflection.IntrospectionExtensions.GetTypeInfo(this.GetType()).Assembly.GetType(string.Concat("ApressDemo.ApressODataService", typeName.Substring(17)));
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ApressDemo.ApressODataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ApressBookDBModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ApressBooks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ApressBook> ApressBooks
        {
            get
            {
                if ((this._ApressBooks == null))
                {
                    this._ApressBooks = base.CreateQuery<ApressBook>("ApressBooks");
                }
                return this._ApressBooks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ApressBook> _ApressBooks;
        /// <summary>
        /// There are no comments for ApressBooks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToApressBooks(ApressBook apressBook)
        {
            base.AddObject("ApressBooks", apressBook);
        }
    }
    /// <summary>
    /// There are no comments for ApressBookDBModel.ApressBook in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ApressBooks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class ApressBook : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ApressBook object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="apressBookISBN">Initial value of ApressBookISBN.</param>
        /// <param name="apressBookName">Initial value of ApressBookName.</param>
        /// <param name="apressBookTechnology">Initial value of ApressBookTechnology.</param>
        /// <param name="apressBookAuthor">Initial value of ApressBookAuthor.</param>
        /// <param name="apressBookPublishedDate">Initial value of ApressBookPublishedDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ApressBook CreateApressBook(int ID, string apressBookISBN, string apressBookName, string apressBookTechnology, string apressBookAuthor, global::System.DateTime apressBookPublishedDate)
        {
            ApressBook apressBook = new ApressBook();
            apressBook.ID = ID;
            apressBook.ApressBookISBN = apressBookISBN;
            apressBook.ApressBookName = apressBookName;
            apressBook.ApressBookTechnology = apressBookTechnology;
            apressBook.ApressBookAuthor = apressBookAuthor;
            apressBook.ApressBookPublishedDate = apressBookPublishedDate;
            return apressBook;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ApressBookISBN in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ApressBookISBN
        {
            get
            {
                return this._ApressBookISBN;
            }
            set
            {
                this.OnApressBookISBNChanging(value);
                this._ApressBookISBN = value;
                this.OnApressBookISBNChanged();
                this.OnPropertyChanged("ApressBookISBN");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ApressBookISBN;
        partial void OnApressBookISBNChanging(string value);
        partial void OnApressBookISBNChanged();
        /// <summary>
        /// There are no comments for Property ApressBookName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ApressBookName
        {
            get
            {
                return this._ApressBookName;
            }
            set
            {
                this.OnApressBookNameChanging(value);
                this._ApressBookName = value;
                this.OnApressBookNameChanged();
                this.OnPropertyChanged("ApressBookName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ApressBookName;
        partial void OnApressBookNameChanging(string value);
        partial void OnApressBookNameChanged();
        /// <summary>
        /// There are no comments for Property ApressBookTechnology in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ApressBookTechnology
        {
            get
            {
                return this._ApressBookTechnology;
            }
            set
            {
                this.OnApressBookTechnologyChanging(value);
                this._ApressBookTechnology = value;
                this.OnApressBookTechnologyChanged();
                this.OnPropertyChanged("ApressBookTechnology");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ApressBookTechnology;
        partial void OnApressBookTechnologyChanging(string value);
        partial void OnApressBookTechnologyChanged();
        /// <summary>
        /// There are no comments for Property ApressBookAuthor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ApressBookAuthor
        {
            get
            {
                return this._ApressBookAuthor;
            }
            set
            {
                this.OnApressBookAuthorChanging(value);
                this._ApressBookAuthor = value;
                this.OnApressBookAuthorChanged();
                this.OnPropertyChanged("ApressBookAuthor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ApressBookAuthor;
        partial void OnApressBookAuthorChanging(string value);
        partial void OnApressBookAuthorChanged();
        /// <summary>
        /// There are no comments for Property ApressBookPublishedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ApressBookPublishedDate
        {
            get
            {
                return this._ApressBookPublishedDate;
            }
            set
            {
                this.OnApressBookPublishedDateChanging(value);
                this._ApressBookPublishedDate = value;
                this.OnApressBookPublishedDateChanged();
                this.OnPropertyChanged("ApressBookPublishedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ApressBookPublishedDate;
        partial void OnApressBookPublishedDateChanging(global::System.DateTime value);
        partial void OnApressBookPublishedDateChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
